[workspace]
members = ["crates/*"]
#default-members = ["crates/bot_lib"]

#[profile.release]
#codegen-units = 1
#lto = true
#strip = true
#panic = "abort"

#[workspace.dependencies]
#conv_to_report = { path = "crates/conv_to_report" }
#bot_lib = { path = "crates/bot_lib" }


