[package]
name = "conv_to_report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# --[ Main ]--
error-stack = { version = "0.2.4", features = ["anyhow"] }
anyhow = "1.0.66"


